/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.deneme4;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class KitapTablosu extends javax.swing.JFrame {

    /**
     * Creates new form KitapTablosu
     */
    public KitapTablosu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kitap_adi = new javax.swing.JTextField();
        yazar_adi = new javax.swing.JTextField();
        basim_yili = new javax.swing.JTextField();
        kitap_turu = new javax.swing.JComboBox<>();
        yayinevi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kitap_tablosu = new javax.swing.JTable();
        ekle_butonu = new javax.swing.JButton();
        kitap_guncelle = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 117, 26));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO BOOKREF");

        kitap_turu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------------------", "Anı", "Anlatı", "Araştırma-İnceleme", "Bilim", "Biyografi", "Çizgi Roman", "Deneme", "Edebiyat", "Eğitim", "Felsefe", "Gençlik", "Gezi", "Hikaye", "Hobi", "İnceleme", "İş Ekonomi - Hukuk", "Kişisel Gelişim", "Konuşmalar", "Masal", "Mektup", "Mizah", "Öykü", "Polisiye", "Psikoloji", "Resimli Öykü", "Roman", "Sağlık", "Sanat - Tasarım", "Sanat- Müzik", "Sinema Tarihi", "Söyleşi", "Şiir", "Tarih", "Yemek Kitapları" }));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel2.setText("Kitap Adı");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel3.setText("Yazar Adı");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel4.setText("Basım Yılı");

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel5.setText("Kitap Türü");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel6.setText("Yayınevi");

        kitap_tablosu.setForeground(new java.awt.Color(255, 51, 0));
        kitap_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap Adı", "Yazar Adı", "Basım Yılı", "Kitap Türü", "Yayınevi"
            }
        ));
        kitap_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitap_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kitap_tablosu);

        ekle_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\ekle.png")); // NOI18N
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        kitap_guncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\guncelle.png")); // NOI18N
        kitap_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitap_guncelleActionPerformed(evt);
            }
        });

        sil_butonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\sil.png")); // NOI18N
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        mesaj_yazisi.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 18)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 133, 16));

        jPanel2.setBackground(new java.awt.Color(252, 117, 26));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 101, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yazar_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kitap_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basim_yili, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kitap_turu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(kitap_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(sil_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kitap_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yazar_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(basim_yili, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kitap_turu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yayinevi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kitap_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sil_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        mesaj_yazisi.setText("");
    DefaultTableModel model = (DefaultTableModel) kitap_tablosu.getModel();

    try {
        String kitapAdi = kitap_adi.getText();
        String yazarAdi = yazar_adi.getText();
        String basimYili = basim_yili.getText();
        String kitapTuru = kitap_turu.getSelectedItem().toString();
        String yayinEvi = yayinevi.getText();

        if (kitapAdi.trim().isEmpty() || yazarAdi.trim().isEmpty()) {
            throw new IllegalArgumentException("Kitap adı veya yazar adı boş bırakılamaz.");
        }
        Object[] eklenecek = {kitapAdi, yazarAdi, basimYili, kitapTuru, yayinEvi};
        model.addRow(eklenecek);
        
        //ArrayList<Kitap> kitapListesi = KitapListesi.getKitapListesi();
        //kitapListesi.add(new Kitap(kitapAdi, yazarAdi, basimYili, kitapTuru, yayinEvi));
        KitapListesi kitapListesi = new KitapListesi(kitapAdi, yazarAdi, basimYili, kitapTuru, yayinEvi);
        kitapListesi.kitapEkle(kitapListesi);
     
    } catch (Exception e) {
        mesaj_yazisi.setText("Hata: " + e.getMessage());
    }
    
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void kitap_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitap_guncelleActionPerformed
        mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) kitap_tablosu.getModel();
        int secili_row = kitap_tablosu.getSelectedRow();
        
        
        if(secili_row == -1){
            if(kitap_tablosu.getRowCount() == 0){
                
                mesaj_yazisi.setText("Kitap Listesi Boş!");
            }
            else{
                mesaj_yazisi.setText("Lutfen guncellenecek urunu secin ");
            }
                       
            
        }
        else{
            model.setValueAt(kitap_adi.getText(),secili_row,0);
            model.setValueAt(yazar_adi.getText(),secili_row,1);
            model.setValueAt(basim_yili.getText(),secili_row,2);
            model.setValueAt(kitap_turu.getSelectedItem(),secili_row,3);
            model.setValueAt(yayinevi.getText(),secili_row,4);
            
        }
        
                
    }//GEN-LAST:event_kitap_guncelleActionPerformed

    private void kitap_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitap_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) kitap_tablosu.getModel();
        int secili_row = kitap_tablosu.getSelectedRow();//Seçilen satırdaki bilgileri kutucuklara yazar.
        
        kitap_adi.setText(model.getValueAt(secili_row,0).toString());
        yazar_adi.setText(model.getValueAt(secili_row,1).toString());
        basim_yili.setText(model.getValueAt(secili_row,2).toString());
        kitap_turu.setSelectedItem(model.getValueAt(secili_row,3).toString());
        yayinevi.setText(model.getValueAt(secili_row,4).toString());
        
       
    }//GEN-LAST:event_kitap_tablosuMouseClicked

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
    mesaj_yazisi.setText("");
    DefaultTableModel model = (DefaultTableModel) kitap_tablosu.getModel();

    try {
        int seciliRow = kitap_tablosu.getSelectedRow();
        if (seciliRow == -1) {
            throw new IllegalArgumentException("Lütfen silmek istediğiniz bir kitap seçin.");
        }
        
        String kitapAdi = kitap_adi.getText();
        String yazarAdi = yazar_adi.getText();
        String basimYili = basim_yili.getText();
        String kitapTuru = kitap_turu.getSelectedItem().toString();
        String yayinEvi = yayinevi.getText();

        Kitap silinecekKitap = new Kitap(kitapAdi, yazarAdi, basimYili, kitapTuru, yayinEvi);
        
        model.removeRow(seciliRow); //Tablodan satırı siler
        
        
        KitapListesi kitapListesi = new KitapListesi(kitapAdi, yazarAdi, basimYili, kitapTuru, yayinEvi);
        kitapListesi.kitapSil(silinecekKitap);//Arraylistten kitabı siler
        
    } catch (Exception e) {
        mesaj_yazisi.setText("Hata: " + e.getMessage());
    }
             
    }//GEN-LAST:event_sil_butonuActionPerformed

   
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KitapTablosu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basim_yili;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kitap_adi;
    private javax.swing.JButton kitap_guncelle;
    private javax.swing.JTable kitap_tablosu;
    private javax.swing.JComboBox<String> kitap_turu;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField yayinevi;
    private javax.swing.JTextField yazar_adi;
    // End of variables declaration//GEN-END:variables
}
